# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewer.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1164, 847)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.browse_tab = QtWidgets.QWidget()
        self.browse_tab.setObjectName("browse_tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.browse_tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.results_tree = QtWidgets.QTreeWidget(self.browse_tab)
        self.results_tree.setObjectName("results_tree")
        self.results_tree.headerItem().setText(0, "1")
        self.horizontalLayout_2.addWidget(self.results_tree)
        self.item_table = QtWidgets.QTableWidget(self.browse_tab)
        self.item_table.setObjectName("item_table")
        self.item_table.setColumnCount(0)
        self.item_table.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.item_table)
        self.tabWidget.addTab(self.browse_tab, "")
        self.sql_tab = QtWidgets.QWidget()
        self.sql_tab.setObjectName("sql_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sql_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sql_input = QtWidgets.QPlainTextEdit(self.sql_tab)
        self.sql_input.setObjectName("sql_input")
        self.verticalLayout_2.addWidget(self.sql_input)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sql_status = QtWidgets.QLabel(self.sql_tab)
        self.sql_status.setText("")
        self.sql_status.setObjectName("sql_status")
        self.horizontalLayout.addWidget(self.sql_status)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_run_sql = QtWidgets.QPushButton(self.sql_tab)
        self.btn_run_sql.setObjectName("btn_run_sql")
        self.horizontalLayout.addWidget(self.btn_run_sql)
        self.btn_sql_export = QtWidgets.QPushButton(self.sql_tab)
        self.btn_sql_export.setObjectName("btn_sql_export")
        self.horizontalLayout.addWidget(self.btn_sql_export)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.sql_table = QtWidgets.QTableWidget(self.sql_tab)
        self.sql_table.setObjectName("sql_table")
        self.sql_table.setColumnCount(0)
        self.sql_table.setRowCount(0)
        self.verticalLayout_2.addWidget(self.sql_table)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(2, 2)
        self.tabWidget.addTab(self.sql_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1164, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setEnabled(False)
        self.actionImport.setObjectName("actionImport")
        self.actionCreate = QtWidgets.QAction(MainWindow)
        self.actionCreate.setObjectName("actionCreate")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionCreate)
        self.menuFile.addAction(self.actionImport)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.browse_tab), _translate("MainWindow", "Browse"))
        self.btn_run_sql.setText(_translate("MainWindow", "Run"))
        self.btn_sql_export.setText(_translate("MainWindow", "Export"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sql_tab), _translate("MainWindow", "SQL"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionImport.setText(_translate("MainWindow", "Import"))
        self.actionCreate.setText(_translate("MainWindow", "Create"))

